name: ci


on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    # - run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      if: ${{ github.ref }} == 'refs/heads/main'

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        tags: | 
          ghcr.io/${{ github.repository }}/go-flare:${{ env.IMAGE_TAG }}