name: container-images


on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: ls -lah

    - run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      if: ${{ github.ref_name }} == 'main'
    - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_UID }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Build and push image
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: | 
          ghcr.io/${{ github.repository }}/go-flare:${{ env.IMAGE_TAG }}
          ${{ secrets.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}